ok, ma ora sistemo getops per opzioni estese

diff --git a/ezscan b/ezscan
--- a/ezscan
+++ b/ezscan
@@ -22,7 +22,7 @@
 VERBOSE=0
 #
 # while getopts :vdsH:P:m:r:Q:t:u:o: opt
-while getopts vhd: opt
+while getopts vhd:B:V: opt
 do
   case "$opt" in
     v) echo "Found the -v (verbose) option"
@@ -32,41 +32,69 @@ do
          echo "Found the -h (help) option"
        fi
        echo "Usage: "
-       echo "ezscan [-v] [OPTION] -d documentroot"
-       echo "ezscan -h"
+       echo "ezscan [-v] [OPTION] "
        echo 
        echo 
        echo "Valid options are: "
        echo
-       echo "   -v              verbose (better if it's the first option)"
-       echo "   -h              help (this page)"
-       echo "   -d              ez document root (default to current directory)"
+       echo "   -d ez_directory   set ez directory (default to current directory)"
+       echo "   -B blockName      eZINI variable blockName you want to see"
+       echo "   -V varName        eZINI variable varName you want to see"
+       echo "   -v                verbose (better if it's the first option)"
+       echo "   -h                help (this page)"
        echo " "
        echo "Ex."
-       echo "./ezscan -d '/home/httpd/myez/html'"
+       echo "ezscan -d /home/httpd/mysite.site.com/html"
+       echo "ezscan -B DatabaseSettings -V User"
+       echo "ezscan -h"
        echo 
        exit;;
-    d) DOCUMENT_ROOT=$OPTARG
+    d) EZ_DIR=$OPTARG
        if [ $VERBOSE -eq 1 ]
        then
          echo "Found the -d (documentroot) option, with value: $OPTARG"
        fi ;;
+    B) EZINI_BLOCK_NAME=$OPTARG
+       if [ $VERBOSE -eq 1 ]
+       then
+         echo "Found the -B (blockName) option, with value: $OPTARG"
+       fi ;;
+    V) EZINI_VAR_NAME=$OPTARG
+       if [ $VERBOSE -eq 1 ]
+       then
+         echo "Found the -V (varName) option, with value: $OPTARG"
+       fi ;;
+
     *) echo "Unknown option: $opt"
        echo "Try 'ezscan -h' for more information."
        exit 1 ;;
   esac
 done
 
+    if (optind < argc) {
+        printf ("non-option ARGV-elements: ");
+        while (optind < argc)
+            printf ("%s ", argv[optind++]);
+        printf ("\n");
+    }
+    exit (0);
 # Test presence of mandatory options
-#if [ -z "$DOCUMENT_ROOT" ]
+#if [ -z "$EZ_DIR" ]
 #then
 #  echo "missing  -d (documentroot) option"
 #  EXIT_FOR_ERROR=yes
 #fi
 
+if ( [ "$EZINI_BLOCK_NAME" ] && [ -z "$EZINI_VAR_NAME" ] ) || ( [ -z "$EZINI_BLOCK_NAME" ] && [  "$EZINI_VAR_NAME" ] )
+then
+  echo "eZIni output needs both blockName & varName must be present"
+  EXIT_FOR_ERROR=yes
+fi
+
+
 if [ $EXIT_FOR_ERROR ]
 then
-  echo "ERROR"
+  #echo "ERROR"
   echo "Try 'ezscan -h'"
   exit 1
 fi
@@ -75,9 +103,9 @@ fi
 #
 # set defaults
 
-if [ -z "$DOCUMENT_ROOT" ]
+if [ -z "$EZ_DIR" ]
 then
-    DOCUMENT_ROOT=`pwd`
+    EZ_DIR=`pwd`
 fi
 
 
@@ -86,23 +114,62 @@ if [ $VERBOSE -eq 1 ]
 then
   echo "executing..."
 fi
-#
-# Ora dobbiamo eseguire una falsa chiamata ad ezp per:
-# 1. controllare di essere all'interno di un dir di eZ
-# 2. popolare le variabili d'ambiente: EZPCOMP_EZ_DIR, EZPCOMP_IS_EZ_DIR, EZPCOMP_PWD
-#
-# ezp * Return values:
-# * - 0: OK
-# * - 1: unknown command
-# * - 2: unknown script
 
-EZP_PATH=`which ezp`
-$EZP_PATH 
-if [ $? -eq 1 ]
+
+EZPCOMP_EZ_DIR=''
+cd $EZ_DIR
+
+# chech if we are inside an eZ Publish directory
+#    populate $EZPCOMP_IS_EZ_DIR, $EZPCOMP_EZ_DIR
+#
+    if [ -n "$EZPCOMP_IS_EZ_DIR" ]; then EZPCOMP_IS_EZ_DIR=0; fi
+    # Exit directly if not in an ezpublish instance
+    CWD=$(pwd)
+    EZPCOMP_PWD=$CWD
+
+    # Reset the previous working directory if it doesn't match the current one
+    if [ -n "$EZPCOMP_PWD" ] || [ "$EZPCOMP_PWD" -ne "$CWD" ]; then
+        #local cwd_array ifs_bak
+        IFS_BAK=$IFS
+        IFS="/"
+    CWD_ARRAY=( $CWD )
+        EZPCOMP_IS_EZ_DIR=0
+    for(( index=${#CWD_ARRAY[*]} ; index > 0 ; index-- ))
+        do
+            testdir="${CWD_ARRAY[*]:0:$index}"
+            #_ezp_p_debug "$index: $testdir/lib/version.php"
+            if [ -f "$testdir/lib/version.php" ]; then
+                #_ezp_p_debug "$testdir did match"
+                EZPCOMP_EZ_DIR="$testdir"
+                EZPCOMP_IS_EZ_DIR=1
+                EZPCOMP_PWD=$CWD
+                export EZPCOMP_EZ_DIR
+                export EZPCOMP_IS_EZ_DIR
+                break
+            fi
+        done
+        IFS=$IFS_BAK
+    fi
+
+if [ $VERBOSE -eq 1 ]
 then
+  echo '$EZPCOMP_EZ_DIR='$EZPCOMP_EZ_DIR
+  echo '$EZPCOMP_IS_EZ_DIR='$EZPCOMP_IS_EZ_DIR
+fi
+
+
+# Not an eZ Dir
+if [ -z "$EZPCOMP_IS_EZ_DIR" ] || [ "$EZPCOMP_IS_EZ_DIR" -eq 0 ]; then
+  echo "You are not in a eZ Publish directory, or the documentroot you supplied is not an eZ Publish directory"
   exit 1
 fi
 
 
-echo $EZPCOMP_EZ_DIR
-echo $EZPCOMP_IS_EZ_DIR
+cd $EZPCOMP_EZ_DIR
+
+PHP_EZSCAN=`which php_ezscan`
+
+#/home/developer/scripts/ezscan_dev/ezscan-php.php $EZINI_BLOCK_NAME $EZINI_VAR_NAME
+if  [ "$EZINI_BLOCK_NAME" ] && [ "$EZINI_VAR_NAME" ] ; then
+  $PHP_EZSCAN  _ini $EZINI_BLOCK_NAME $EZINI_VAR_NAME
+fi
